### ISSUE TITLE
How this scheduler could be adapted to Nuvolaris

### ISSUE THREAD

**Issue by msciabarra** [francescotimperi/io-sdk-scheduler#11]
I am not sure how much work it would be, however, this is how I see the scheduler:

- it should be a long running process that is activated every minute

- an action can have a cron annotation like this: 'cron: "* * * * *"' that means "every minute", or 'cron: 0 * * * *' that means at minute 0 of the hour... and so on'

- it should check all the actions and look for annotations [see  #2 for details] - assume you have a list_cron_actions() that returns an array of:
```
{
  "action": '/namespace/package/action",
   "apikey" 'apikey-to-invoke-the-action",
   "cron": 'a cron expression'
}
```

- if the current time matches the cron expression it just invoke it using the [openwhisk api](https://github.com/apache/openwhisk/blob/master/docs/rest_api.md)

**Comment by francescotimperi** [comment]
One possible approach could be

- Implement a nuvolaris action which returns the cron aware actions
- Create a Job implementation that is capable of executing the above Nuvolaris action and parse the response. The implemented one is capable of executing a command line (it was tested with the wsk cli back in time)
- Schedule the above implemented Job when the scheduler starts for execution every minutes.

Anyway I am not really sure this will be efficient when the number of actions is increasing. 

What about something like this.

- Implement a generic Job which is capable of running a nuvolaris action via the Nuv command line.
- when a nuvolaris action is deployed with cron argument a new job instance is inserted into the scheduler via the exposed REST API. Of course this means that the Nuv cli needs to interact with the scheduler API to add/remove such job.
- when the scheduler trigger a job it calls the scheduled action using the wsk cli

**Comment by msciabarra** [comment]
1. extracting the actions with the annotations data using a "system" action is actually a good idea, so we can hide some of the details of the database inside this action.


2. about the job I am not sure is a good idea because of the overhead of launching a job... Honestly I cannot assess if it is better to keep a pod always running in sleep mode or using a job.
3. I do not care of the "large" number. They can be thousands, it is still a small number (they never will be millions). It happens only once in a minute and it is manageable even with a very constrained environment.


Regarding the proposal... it is not a bad idea. Let me think about. Will come back later.

**Comment by msciabarra** [comment]
The schedules can be implemented with:

1. one nuvolaris system action that will return a list of actions that should be triggered "now" reading the database directly (the operator can deploy it with the required secrets).
2. one scheduled job that will invoke the actions - but no need to use nuv: there are all the apis we need in [javascript](https://www.npmjs.com/package/openwhisk) 


The only thing I am not sure if it is better to have a long running pod or a periodical job...

**Comment by francescotimperi** [comment]
The current scheduler implementation starts a node.js application in a docker container so it is somehow ready for a long running pod (1 and only 1 ). But this pod makes sense if we would like to have the job scheduled via the Nuvolaris cli at deploy time.  It means that the scheduler process will contains as many job as the scheduled ones and triggers them accordingly. Having the pod gives the possibility to get the list of the scheduled job querying directly the scheduler instead of accessing the actions internal database, so somehow it will not be needed to develop the nuvolaris system action at previous point 1 (or at least it is not mandatory to have it).

For the periodical job, you mean a process that should be scheduled via the OS crontab? Or something similar?

**Comment by msciabarra** [comment]
You convinced me to use a crontab. Somethink like this:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ghc.io/nuvloaris/nuvolaris-operator:xxx
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - ./run-scheduled-actions.sh
          restartPolicy: OnFailure
```

the command run-scheduled-action will use the python library in  the operator that is already available to read and write in couchdb.

I already use the image of the operator to run the couchdb initialization so it is the easier way.

**Comment by msciabarra** [comment]
Superceded by [this issue](https://github.com/nuvolaris/nuvolaris/issues/114)
